	charmap "0",	$a0
	charmap "1",	$a2
	charmap "2",	$a4
	charmap "3",	$a6
	charmap "4",	$a8
	charmap "5",	$aa
	charmap "6",	$ac
	charmap "7",	$ae
	charmap "8",	$b0
	charmap "9",	$b2

	charmap "A",	$b4
	charmap "B",	$b6
	charmap "C",	$b8
	charmap "D",	$ba
	charmap "E",	$bc
	charmap "F",	$be
	charmap "G",	$c0
	charmap "H",	$c2
	charmap "I",	$c4
	charmap "J",	$c6
	charmap "K",	$c8
	charmap "L",	$ca
	charmap "M",	$cc
	charmap "N",	$ce
	charmap "O",	$d0
	charmap "P",	$d2
	charmap "Q",	$d4
	charmap "R",	$d6
	charmap "S",	$d8
	charmap "T",	$da
	charmap "U",	$dc
	charmap "V",	$de
	charmap "W",	$e0
	charmap "X",	$e2
	charmap "Y",	$e4
	charmap "Z",	$e6

	charmap ".",	$e8
	charmap "-",	$e9

	charmap "0",	$f0
	charmap "1",	$f1
	charmap "2",	$f2
	charmap "3",	$f3
	charmap "4",	$f4
	charmap "5",	$f5
	charmap "6",	$f6
	charmap "7",	$f7
	charmap "8",	$f8
	charmap "9",	$f9
